
# Global Configuration
global:
  project_name: "AFT-Multi-Region-Security-Group-Quota-Automation"
  version: "2.0"
  description: "Automated Security Group quota increases across multiple AWS regions"
  automation_type: "multi-region"
  
# Security Group Quota Configuration
security_group_quota:
  service_code: "vpc"
  quota_code: "L-0EA8095F"
  quota_name: "Inbound or outbound rules per security group"
  current_default_value: 60
  target_default_value: 200
  
# Multi-Region Configuration
regional_configuration:
  # Default regions to target (can be overridden per account)
  default_regions:
    - "us-east-1"      # Required for global services
    - "eu-west-2"      # Primary European region
    - "ap-southeast-1" # Primary Asia-Pacific region
    
  # Per-region quota settings
  regional_settings:
    us-east-1:
      enabled: true
      target_value: 200
      priority: "high"
      description: "US East (N. Virginia) - Global services region"
      
    eu-west-2:
      enabled: true
      target_value: 200
      priority: "high"
      description: "Europe (London) - Primary European region"
      
    us-west-2:
      enabled: true
      target_value: 200
      priority: "medium"
      description: "US West (Oregon) - Secondary US region"
      
    ap-southeast-1:
      enabled: true
      target_value: 200
      priority: "medium"
      description: "Asia Pacific (Singapore) - Primary Asia region"
      
    ap-southeast-2:
      enabled: false
      target_value: 200
      priority: "low"
      description: "Asia Pacific (Sydney) - Secondary Asia region"
      
    eu-central-1:
      enabled: false
      target_value: 200
      priority: "low"
      description: "Europe (Frankfurt) - Secondary European region"
      
    ca-central-1:
      enabled: false
      target_value: 200
      priority: "low"
      description: "Canada (Central) - Canadian region"

# Deployment Strategy
deployment:
  strategy: "parallel"  # Options: parallel, sequential
  timeout_minutes: 30
  retry_attempts: 3
  retry_delay_seconds: 60
  
# Validation Configuration
validation:
  enabled: true
  timeout_minutes: 15
  check_intervals_seconds: 30
  validate_all_regions: true
  
  # Validation checks
  checks:
    - "quota_request_submission"
    - "terraform_state_validation"
    - "regional_quota_values"
    - "request_status_tracking"

# Monitoring and Alerting
monitoring:
  enabled: true
  quota_utilization_threshold: 80
  alert_on_failures: true
  track_request_history: true
  
  # Metrics to collect
  metrics:
    - "quota_requests_submitted"
    - "quota_requests_approved"
    - "quota_requests_denied"
    - "current_quota_values"
    - "quota_utilization_percentage"

# AFT Integration Settings
aft_integration:
  trigger_on_account_creation: true
  run_in_global_customizations: true
  support_account_updates: true
  
  # AFT-specific settings
  execution_role: "AWSAFTExecution"
  session_name_prefix: "AFT-QuotaRequest"
  
# Business Justification
business_justification:
  default_reason: >
    Multi-region automated quota increase for Security Group rules to support 
    operational requirements. Increasing from default 60 to 200 rules per 
    security group to accommodate application security requirements across 
    multiple AWS regions for scalable and secure workload deployment.
    
  compliance_requirements:
    - "Support for microservices architecture requiring complex security rules"
    - "Multi-region disaster recovery and high availability requirements"
    - "Compliance with enterprise security standards"
    - "Automated infrastructure provisioning at scale"

# Error Handling and Resilience
error_handling:
  continue_on_region_failure: true
  log_all_failures: true
  create_failure_reports: true
  
  # Retry logic
  retry_on_transient_errors: true
  transient_error_codes:
    - "Throttling"
    - "ServiceUnavailable"
    - "InternalError"
    
# Advanced Features
advanced_features:
  # Account-specific overrides
  account_overrides:
    enabled: true
    override_file: "account-specific-quotas.yaml"
    
  # Conditional deployment
  conditional_deployment:
    enabled: true
    conditions:
      - "account_has_workloads_in_region"
      - "region_is_enabled_for_organization"
      
  # Quota templates for different account types
  quota_templates:
    production:
      target_value: 300
      priority: "high"
      regions: ["us-east-1", "eu-west-2", "ap-southeast-1"]
      
    development:
      target_value: 150
      priority: "medium"
      regions: ["us-east-1", "eu-west-2"]
      
    sandbox:
      target_value: 100
      priority: "low"
      regions: ["us-east-1"]

# Maintenance and Updates
maintenance:
  auto_update_enabled: false
  update_schedule: "monthly"
  backup_configurations: true
  
  # Version management
  version_control:
    track_changes: true
    require_approval: true
    rollback_capability: true
