# AFT Security Group Quota Configuration
global:
  service_code: "vpc"
  quota_code: "L-0EA8095F"
  current_default: 60
  target_default: 200

regions:
  us-east-1:
    enabled: true
    target_value: 200
    priority: high
    
  eu-west-2:
    enabled: true
    target_value: 200
    priority: high
    
  us-west-2:
    enabled: true
    target_value: 200
    priority: medium
    
  ap-southeast-1:
    enabled: true
    target_value: 200
    priority: medium

deployment:
  strategy: parallel
  timeout_minutes: 30
  retry_attempts: 3
  
validation:
  enabled: true
  check_intervals: 30

aft_settings:
  execution_role: "AWSAFTExecution"
  session_prefix: "AFT-QuotaRequest"